In [2]:
import sklearn.naive_bayes as naive_bayes
from sklearn.cross_validation import train_test_split
import numpy as np

# 16/01/2017

In [3]:
h1=np.array([1,0,0,0])
h2=np.array([1,0,0,1])
h3=np.array([0,1,1,0])

In [17]:
d1=np.array([0.2,0.3,0.3,0.2])
eg1=(h1*d1).sum()
eg2=(h2*d1).sum()
eg3=(h3*d1).sum()
print eg1, eg2, eg3

0.2 0.4 0.6


In [26]:
d2=np.array([0.5,0.2,0.3,0.00])
ee1=(h1*d2).sum()
ee2=(h2*d2).sum()
ee3=(h3*d2).sum()
print ee1, ee2, ee3


0.5 0.5 0.5


In [31]:
np.power(4,0.5)

2.0

In [32]:
np.power((1-2/2.0), 0.5)

0.0

In [50]:
e=0.999

np.power(((1-e)/e),0.5)

0.031638599858416647

In [45]:
np.power(2.0, -2)

0.25

In [51]:
ep=0.3

0.5*(np.log((1-ep)/ep))

0.42364893019360184

# 07/01/2017

In [23]:
0.5*0.75+0.5*0.4

0.575

In [24]:
0.75*0.2

0.15000000000000002

In [25]:
0.75*0.2/0.575

0.26086956521739135

In [22]:
0.75*0.2

0.15000000000000002

In [28]:
6.0/23

0.2608695652173913

In [16]:
0.5*0.6

0.3

In [18]:
0.3*0.375

0.11249999999999999

In [19]:
0.2*0.375

0.07500000000000001

In [20]:
0.3*0.375+0.2*0.375

0.1875

In [14]:
(0.5*0.75)/(0.5*0.4*0.5)

3.75

In [ ]:
0.5*0.6/(0.5*0.75*0.5)

In [9]:
0.25/0.65

0.3846153846153846

In [10]:
0.05/0.35

0.14285714285714288

In [11]:
0.20/0.25

0.8

In [13]:
0.03/0.30

0.1

In [1]:
0.25*0.20

0.05

In [2]:
0.25*0.05

0.0125

In [3]:
0.40*0.09

0.036

In [4]:
0.40*0.36

0.144

In [5]:
0.05*0.04

0.002

In [6]:
0.05*0.01

0.0005

In [7]:
0.30*0.03

0.009

In [8]:
0.30*0.27

0.081

# 06/01/2017

In [2]:
x=[1,3,6,10,11,13]
d=[1,0,5,2,1,4]

In [14]:
h1=np.mod(x, 9)
h2=np.float32(x)/3
h3=[2,2,2,2,2,2]

In [16]:
h1-d

array([ 0,  3,  1, -1,  1,  0])

In [18]:
np.power((d-h1),2).sum()

12

In [19]:
np.power((d-h2),2).sum()

19.444444749090444

In [22]:
np.power((np.array(d)-np.array(h3)),2).sum()

19

In [24]:
(1.0/3)*0.4

0.13333333333333333

In [25]:
(2.0/3)*0.3

0.19999999999999998

# 04/01/2017

In [6]:
P_sp=0.008
P_nsp=0.992
P_pos_given_sp=0.98
P_neg_given_sp=0.02
P_neg_given_nsp=0.97
P_pos_given_nsp=0.03

In [7]:
P_pos=P_pos_given_sp*P_sp+P_pos_given_nsp*P_nsp


In [8]:
P_sp_given_pos=(P_pos_given_sp*P_sp)/P_pos

In [9]:
P_sp_given_pos

0.20851063829787236

In [10]:
P_pos

0.037599999999999995

# 03/01/2017

In [11]:
P_Chris=0.5
P_Sara=0.5
P_LD_Given_Chris=0.04
P_LD_Given_Sara=0.03

In [10]:
P_LD=0.5*0.04+0.5*0.03

In [12]:
P_LDandChris=P_Chris*P_LD_Given_Chris
P_LDandSara=P_Sara*P_LD_Given_Sara

In [13]:
P_Chris_given_LD=P_LDandChris/P_LD
P_Sarah_given_LD=P_LDandSara/P_LD

In [14]:
P_Chris_given_LD

0.5714285714285714

In [15]:
P_Sarah_given_LD

0.4285714285714285

In [16]:
P_LD

0.035

In [17]:
P_LDandChris

0.02

In [18]:
P_LoD_given_Chris=0.5*0.1*0.8
P_LoD_given_Sarah=0.5*0.5*0.2

In [19]:
P_LoD_given_Chris/(P_LoD_given_Chris+P_LoD_given_Sarah)

0.4444444444444445

In [20]:
P_LoD_given_Sarah/(P_LoD_given_Chris+P_LoD_given_Sarah)

0.5555555555555555

In [3]:
0.01*0.9/(0.01*0.9+0.99*0.1)

0.08333333333333333

In [4]:
0.99*0.1/(0.01*0.9+0.99*0.1)

0.9166666666666666

In [5]:
0.0833+0.9167

1.0

In [6]:
0.5*0.1*0.8

0.04000000000000001

In [8]:
0.5*0.3*0.2

0.03

# 28/10/2016

In [1]:
37+12+24+33+17+17+11+24+12+28+13+16+10+19+4

277

# 20/10/2016 - machine learning metrices

In [ ]:
clf=naive_bayes.GaussianNB()

In [1]:
score1=10
print "Decision Tree has accuracy: ", score1

Decision Tree has accuracy:  10


Confusion matrix for this Decision Tree:
[[112  39]
 [ 35  37]]
GaussianNB confusion matrix:
[[126  25]
 [ 44  28]]
The answer you've submitted is: 
{'Naive Bayes': array([[126,  25],
                       [ 44,  28]]),
 
 'Decision Tree': 
         array([[112,  39],
                [ 35,  37]])}
                           
                           
TN FP

FN TP

In [ ]:
from sklearn.cross_validation import train_test_split
# TODO: split the data into training and testing sets,
# using the standard settings for train_test_split.
# Then, train and test the classifiers with your newly split data instead of X and y.



X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.4, random_state=0) 

clf1 = DecisionTreeClassifier()
clf1.fit(X_train,y_train)
recall1=recall(y_test,clf1.predict(X_test))
precision1=precision(y_test,clf1.predict(X_test))

print "Decision Tree recall: {:.2f} and precision: {:.2f}".format(recall1,precision1)


clf2 = GaussianNB()
clf2.fit(X_train,y_train)
recall2=recall(y_test,clf1.predict(X_test))
precision2=precision(y_test,clf1.predict(X_test))

print "GaussianNB recall: {:.2f} and precision: {:.2f}".format(recall2,precision2)

results = {
  "Naive Bayes Recall": recall2,
  "Naive Bayes Precision": precision2,
  "Decision Tree Recall": recall1,
  "Decision Tree Precision": precision1
}

Decision Tree recall: 0.51 and precision: 0.56
GaussianNB recall: 0.38 and precision: 0.61
The answer you've submitted is: {'Decision Tree Recall': 0.51470588235294112, 'Naive Bayes Recall': 0.38235294117647056, 'Decision Tree Precision': 0.56451612903225812, 'Naive Bayes Precision': 0.61176470588235299}

Decision Tree F1 score: 0.50
GaussianNB F1 score: 0.47
The answer you've submitted is: {'Naive Bayes': 0.47058823529411764, 'Decision Tree': 0.49618320610687028}

In [ ]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.4, random_state=0) 


reg1 = DecisionTreeRegressor()
reg1.fit(X_train, y_train)
mae1=mae(y_test, reg1.predict(X_test))
print "Decision Tree mean absolute error: {:.2f}".format(mae1)

reg2 = LinearRegression()
reg2.fit(X_train, y_train)
mae2=mae(y_test, reg2.predict(X_test))
print "Linear regression mean absolute error: {:.2f}".format(mae2)

results = {
 "Linear Regression": mae2,
 "Decision Tree": mae1
}