In [3]:
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

In [9]:
X = np.arange(9).reshape(3, 3)
print X

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
poly = PolynomialFeatures(2)
print(poly.fit_transform(X))

[[  1.   0.   1.   0.   0.   1.]
 [  1.   2.   3.   4.   6.   9.]
 [  1.   4.   5.  16.  20.  25.]]


In [10]:
poly = PolynomialFeatures(2, interaction_only=True)
print(poly.fit_transform(X))

[[  1.   0.   1.   2.   0.   0.   2.]
 [  1.   3.   4.   5.  12.  15.  20.]
 [  1.   6.   7.   8.  42.  48.  56.]]


In [13]:
import numpy as np

sleep = [5,6,7,8,10,12,16]
scores = [65,51,75,75,86,80,0]


coeffs=np.polyfit(sleep, scores, 2)

print coeffs
# coeffs = []

[ -1.80827085  33.59928326 -71.3685104 ]


In [1]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [2]:
clf=DecisionTreeClassifier(min_samples_split=2)
clf.fit()

TypeError: fit() takes at least 3 arguments (1 given)

In [10]:
-(0.67*np.log2(0.67)+0.33*np.log2(0.33))

0.91492637277972744

In [12]:
1-0.75*0.9184+0.25*0

0.31120000000000003

In [2]:
3.0/8

0.375